---
- name: Install nodejs
  apt:
    name: nodejs
    state: latest
  register: node

- name: Install npm
  apt:
    name: npm
    state: latest

- name: Verify npm installation
  shell: "npm -v"
  register: npm

- name: Verify nodejs version
  shell: "nodejs -v"
  register: nodejs

- name: Print npm version
  when: npm is changed
  debug:
    msg: "npm version: {{ npm.stdout_lines }}"

- name: Print nodejs version
  when: nodejs is changed
  debug: 
    msg: "Nodejs version: {{ nodejs.stdout_lines }}"

- name: Download source code
  git:
    repo: "https://github.com/contentful/the-example-app.nodejs.git"
    dest: "/apps/NodeApp"

- name: Change the ownership of the directory
  become: yes
  file:
    path: "/apps/NodeApp"
    owner: "workshop"
  register: chgrpout

- name: Install Dependencies with NPM install command
  shell:
    "npm install"
  args:
    chdir: "/apps/NodeApp/"
  register: npminstlout

- name: Debug npm install command
  debug: msg='{{npminstlout.stdout_lines}}'

- name: Start the App
  async: 10
  poll: 0
  shell:
    npm start
  args:
    chdir: "/apps/NodeApp/"

# - name: Validating the port is open
#   tags: nodevalidate
#   wait_for:
#     host: "localhost"
#     port: 3000
#     delay: 10
#     timeout: 30
#     state: started
#     msg: "NodeJS server is not running"