### DO NOT CHANGE SETTINGS ###
version: "3.3" 

# TODO expose configuration folder to ansible container with ansible playbook and etc?
services:
  ansible:
    build:
      context: ./ansible/
      dockerfile: Dockerfile
    container_name: ansible_container
    hostname: ansible_host
    ports:
      - 8080:8080
    volumes:
      - ./configuration/:/ansible/configuration
      - ./ansible.cfg:/etc/ansible/ansible.cfg
      - ./hosts:/etc/ansible/hosts
    networks: 
      internal:

  test1:
    build:
      context: ./test/
      dockerfile: Dockerfile
    container_name: test_container_1
    hostname: test_container_1
    ports:
      - 22:22
    networks:
      internal:

  test2:
    build:
      context: ./test/
      dockerfile: Dockerfile
    container_name: test_container_2
    hostname: test_container_2
    ports:
      - 22:22
    networks:
      internal:

  test3:
    build:
      context: ./test/
      dockerfile: Dockerfile
    container_name: test_container_3
    hostname: test_container_3
    ports:
      - 22:22
    networks:
      internal:

  test4:
    build:
      context: ./test/
      dockerfile: Dockerfile
    container_name: test_container_4
    hostname: test_container_4
    ports:
      - 22:22
    networks:
      internal:

  mongo:
    build:
      context: ./database/
      dockerfile: Dockerfile
    container_name: mongo_container
    hostname: mongo_container
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
    networks:
      internal: 

networks: 
  internal: