### DO NOT CHANGE SETTINGS ###
version: "3.3" 

# TODO expose configuration folder to ansible container with ansible playbook and etc?
services:
  ansible:
    build: .
    container_name: ansible_container
    hostname: ansible_host
    ports:
      - 8080:8080
    networks: 
      internal:

  postgres:
    image: postgres:latest
    container_name: postgres_container
    hostname: postgres_host
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

networks: 
  internal: