---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Get IPAddress
  shell: ip a
  register: result

- name: Print IPAddress
  debug:
     msg: "{{ result.stdout_lines }}"