---
- hosts: webserver
  become: yes

  # tasks:
    # - name: test connection
    #   ping:

    # - name: print statement
    #   ansible.builtin.debug: 
    #     msg: Hello world!

    # - name: install apache2 httpd
    #   apt: 
    #     name: apache2
        
    # - name: uninstall apache2 httpd
    #   apt:
    #     name: apache2
    #     state: absent

    # - name: Read file
    #   shell: cat hello.txt
    #   register: result
    
    # - name: Print file
    #   set_fact:
    #     data: "{{result.stdout}}"

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Find active directory
      shell: pwd
      register: result
    
    - name: Print active directory
      set_fact:
        data: "{result.stdout}}"

    - name: Add index.html file
      template:
        src: /usr/ubuntu/webserver/index.html
        dest: /usr/share/nginx/html/index.html

    - name: Start Nginx
      service:
        name: nginx
        state: started

  # tasks:
  #   - name: create database
  #     community.mongodb.mongodb_user:
  #       login_host: mongo_container
  #       login_user: root
  #       login_password: example
  #       database: admin
  #       name: root