---
- hosts: all
  become: yes

  tasks:
    - name: test connection
      ping:

    - name: print statement
      ansible.builtin.debug: 
        msg: Hello world!

    - name: install apache2 httpd
      apt: 
        name: apache2
        
    - name: uninstall apache2 httpd
      apt:
        name: apache2
        state: absent

    - name: Read file
      shell: cat hello.txt
      register: result
    
    - name: Print file
      set_fact:
        data: "{{result.stdout}}"

  # tasks:
  #   - name: create database
  #     community.mongodb.mongodb_user:
  #       login_host: mongo_container
  #       login_user: root
  #       login_password: example
  #       database: admin
  #       name: root