---
- hosts: all
  become: yes

  tasks:
# Assignment 1 - /roles/verification/tasks/main.yml
  - name: Verify connection to host machines
    import_role:
      name: verification
    tags: verification

# Assignment 2 - /roles/printer/tasks/main.yml
  - name: Print contents of a file
    when: inventory_hostname in groups['default_container']
    import_role:
      name: printer
    tags: printer

    # - name: Install and start nginx
    #   when: inventory_hostname in groups['web_container']
    #   import_role:
    #     name: webserver
    
    # - name: Pull and execute Docker container
    #   when: inventory_hostname in groups['git_container']
    #   import_role:
    #     name: git

    # - name: Install and setup PostgreSQL on host
    #   when: inventory_hostname in groups['database']
    #   import_role:
    #     name: database
    #     tasks_from: install

    # - name: PostgreSQL database interaction
    #   when: inventory_hostname in groups['database']
    #   become: yes
    #   become_user: postgres
    #   import_role:
    #     name: database
    #     tasks_from: main
