---
- hosts: all
  become: yes

  # tasks:
    # - name: test connection
    #   ping:

    # - name: print statement
    #   ansible.builtin.debug: 
    #     msg: Hello world!

    # - name: install apache2 httpd
    #   apt: 
    #     name: apache2
        
    # - name: uninstall apache2 httpd
    #   apt:
    #     name: apache2
    #     state: absent

  tasks:
    - name: Print contents of a file
      when: inventory_hostname in groups['default']
      import_role:
        name: printer

    - name: Install and start nginx
      when: inventory_hostname in groups['webserver']
      import_role:
        name: webserver

  # tasks:
  #   - name: create database
  #     community.mongodb.mongodb_user:
  #       login_host: mongo_container
  #       login_user: root
  #       login_password: example
  #       database: admin
  #       name: root